name: Java CI - Sistema Bancario BBVA (Java 21 + JUnit)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Compilar proyecto
      run: |
        javac -cp lib/junit-platform-console-standalone-1.10.2.jar *.java

    - name: Ejecutar pruebas JUnit
      run: |
        java -jar lib/junit-platform-console-standalone-1.10.2.jar \
        --class-path . \
        --scan-class-path
